export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const  REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';
export const INITIATE_PAYMENT_SUCCESS = 'INITIATE_PAYMENT_SUCCESS'
export const INITIATE_PAYMENT_FAIL = 'INITIATE_PAYMENT_FAIL'
export const PAYMENT_FAIL = 'PAYMENT_FAIL'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const GET_USER = 'GET_USER'


